### ISSUE TITLE
Bug: Installing the Package Changes Execution Policy

### ISSUE THREAD

**Issue by shurick81** [jordigg/chocolatey-officebusiness#12]
I got an interesting behavior that before installing this package, Get-ExecutionPolicy returns "RemoteSigned" but some time after starting installation and also after the installation is over, this command returns "Restricted". I suggest that even if this change is necessary for installation, it should be set back after installation is over.

**Comment by jordigg** [comment]
@shurick81, is this still an issue? The package itself doesn't change this setting, this could be a bug within Chocolatey itself but I haven't been able to reproduce.
