### ISSUE TITLE
Office365Business install overwrites values from custom XML configuration file

### ISSUE THREAD

**Issue by TremendousTurtle** [jordigg/chocolatey-officebusiness#20]
The install script correctly loads all the values from a custom XML config file specified with the` /configpath` option. However, it then overwrites whatever is in the file with any other options specified (`/productid`, `/exclude`, etc) and/or the default values specified in the script.

Currently the `/configpath` option appears to work more like "save the generated configuration file to this location" instead of "load a configuration XML file from this location".

It should be changed to not allow any other options to be specified with /configpath and to just pass the specified path along to the office setup.exe /configure switch without adding or changing anything.

**Comment by jordigg** [comment]
Thanks for reporting. I have merged and uploaded a new version (13530.20376) to choco.
