### ISSUE TITLE
Office installs successfully, but choco package never reports as installed

### ISSUE THREAD

**Issue by jackmtpt** [jordigg/chocolatey-officebusiness#45]
We're installing this package with the following command line:

`choco install Office365Business --parameters '/productid:ProPlus2019Retail /eula /exclude:Access OneNote Outlook PowerPoint Publisher Lync Word OneDrive'`

Excel is successfully installed, but the package never shows up in `choco list` as having been installed. This is breaking our automation because it's never able to detect that the installation has actually finished.

**Comment by jordigg** [comment]
As discussed at the choco site, seems to be related to your environment in specific or the way the MS installer works. Unfortunately the package just orchestrates the installation, error codes comes from the MS package directly which we don't have permissions over.

I'll keep this issue open for a bit just in case. For now, not much we can do on our side.
