### ISSUE TITLE
make ProductID configurable and introduce configurable exclude options

### ISSUE THREAD

**Issue by ctr49** [jordigg/chocolatey-officebusiness#9]
Would you be willing to accept a patch to make the Product ID configurable via install arguments? This may allow the package to be used for other subscriptions types (including retail and home).

Following that path, it would also be possible to introduce ExcludeApp statements for some components, i.e. to only install Word, Excel Powerpoint instead of the entire suite (of course also being configurable with install arguments, installing everything - as is - by default).

I'd be willing to contribute the necessary patches (with #5 being a prerequisite).

If you don't agree, I would like to fork your package and make it available on chocolatey with the suggested changes. If that is your preferred path, please let me know if you have any reservations or suggestions regarding namespace and mentioning / giving credit to contributors of this version.

**Comment by jordigg** [comment]
Hi @ctr49, thanks for your message.

That contribution would be great. Due lack of time on my side I keep maintaining these packages using the same "deploy tool"with specific hard coded packages.
Would be great to make this modular and dynamic so we can offer a single package that installs all apps by default or use a exclude/include parameter to specify which packages should be omitted or installed.

Thanks for helping on this. Any permissions you need on the package or the repo itself, feel free to ask.

**Comment by ctr49** [comment]
Any comments to my suggested approach in the draft PR?
This works fine for me but I cannot tell what the impact to installed user base would be.
If you think it's not a good idea, I'd rather create a new package...

**Comment by jordigg** [comment]
Sorry about the delay @ctr49, lots going on ATM. I'm reviewing and testing now.
Do you want to become a contributor to the package here and also on the choco website?

**Comment by Leftier** [comment]
Exclusions only work when installing the package for the first time...
All the excluded apps will be installed if there is an update or and office automatic update.
Even when useRememberedArgumentsForUpgrades is enabled
